import { useState } from "react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";

interface AIRealmInsightProps {
  realmNumber: number;
  realmName: string;
  theme: string;
  userProgress?: number;
}

export default function AIRealmInsight({
  realmNumber,
  realmName,
  theme,
  userProgress = 0,
}: AIRealmInsightProps) {
  const [insight, setInsight] = useState<string | null>(null);

  const { refetch, isFetching } = trpc.ai.getRealmInsight.useQuery(
    {
      realmNumber,
      realmName,
      theme,
      userProgress,
    },
    {
      enabled: false, // Don't auto-fetch, only on button click
    }
  );

  const handleGenerateInsight = async () => {
    const result = await refetch();
    if (result.data) {
      setInsight(result.data);
    } else if (result.error) {
      toast.error(`Failed to generate insight: ${result.error.message || 'Unknown error'}`);
    }
  };

  if (insight) {
    return (
      <div className="space-y-4">
        <div className="prose prose-invert max-w-none">
          <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">
            {insight}
          </p>
        </div>
        <Button
          onClick={handleGenerateInsight}
          disabled={isFetching}
          variant="outline"
          size="sm"
          className="border-purple-600 text-purple-300 hover:bg-purple-950/50"
        >
          {isFetching ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2" />
              Generate New Insight
            </>
          )}
        </Button>
      </div>
    );
  }

  return (
    <div className="text-center py-8 space-y-4">
      <p className="text-gray-400">
        Receive personalized spiritual guidance for this realm, generated by AI based on your journey.
      </p>
      <Button
        onClick={handleGenerateInsight}
        disabled={isFetching}
        className="bg-gradient-to-r from-purple-600 to-purple-800 hover:from-purple-700 hover:to-purple-900"
      >
        {isFetching ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Generating Insight...
          </>
        ) : (
          <>
            <Sparkles className="w-4 h-4 mr-2" />
            Generate AI Insight
          </>
        )}
      </Button>
    </div>
  );
}
